### ISSUE TITLE
Checklist for week 1 (2020-11-19 to 2020-11-27)

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/acanban#25]
Here are tasks that need to be done:

- [ ] Collect academic templates (#20)
- [ ] Finalizing #19 on security (assigned to @Yus147)
- [ ] Drafting analysis for creating project (sequence diagram, VOPC, ...)
- [ ] Start implementing the first use case: authentication (*)
- [ ] Deploying the server with minimal functionality (e.g. viewing homepage)
- [ ] Revising UC model and database (related: #22 )

(*) I suppose there is some packages that help implementing this without A&D so we can go directly to implementation.

**Comment by McSinyx** [comment]
> Drafting analysis for creating project

-1 from me: it's awkward to make everything a class doing ASGI (or WSGI even),

**Comment by McSinyx** [comment]
Closing in favor of [milestone 0.0.1](https://github.com/Huy-Ngo/acanban/milestone/1).  Some tasks listed here ain't got their tracking issue, feel free to file and add them to the milestone.
